"""GET /audit/{trace_id} — replayability endpoint backing the audit trail feature."""
import pytest
from httpx import ASGITransport, AsyncClient

from backend.main import app


@pytest.mark.asyncio
async def test_audit_trail_returns_events_for_known_trace():
    payload = {
        "type": "tool_call", "conversation_id": "conv_audit_trail_test", "tool_name": "trigger_fault_response",
        "parameters": {"fault_code": "SPN 4334 FMI 18", "load_number": "LOAD-AUDIT"},
    }
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        webhook_resp = await client.post("/webhook/tool-call", json=payload)
        assert webhook_resp.status_code == 200

        # Recover the trace_id the webhook generated by reading it back off the audit
        # trail via the conversation_id — simplest way to get it without parsing logs.
        from backend import audit_log
        conn = audit_log._get_conn()
        row = conn.execute(
            "SELECT trace_id FROM audit_events WHERE conversation_id = ? ORDER BY id DESC LIMIT 1",
            ("conv_audit_trail_test",),
        ).fetchone()
        assert row is not None
        trace_id = row[0]

        resp = await client.get(f"/audit/{trace_id}")
    assert resp.status_code == 200
    body = resp.json()
    assert body["trace_id"] == trace_id
    assert len(body["events"]) > 0
    assert any(e["type"] == "voice_reply_ready" for e in body["events"])


@pytest.mark.asyncio
async def test_audit_trail_empty_for_unknown_trace():
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        resp = await client.get("/audit/nonexistent_trace_id")
    assert resp.status_code == 200
    assert resp.json()["events"] == []
